### ISSUE TITLE
Installer next steps are confusing

### ISSUE THREAD

**Issue by tas50** [mondoohq/installer#302]
**Describe the bug**
When installing the mondoo package I get this text:

```
* No registration token provided, skipping mondoo package for cnquery and cnspec registration.

mondoo package for cnquery and cnspec is ready to go!

Next you should register mondoo package for cnquery and cnspec to get access to policies and reports.
Follow this guide:
```

There's a few confusing parts here

- Repeated usage of `mondoo package for cnquery and cnspec` when I went in to install cnspec is really confusing. As a user that came in for cnspec I have no idea what this package is.
- Text says "ready to go" and then instantly tells me I need to register. Both of those statements can't be true.

**Comment by benr** [comment]
Language for 'Next steps' updated for clarity: https://github.com/mondoohq/installer/blob/main/install.sh#L705

**Comment by benr** [comment]
@tas50 Regarding the name of the package as 'modnoo package for cnquery and cnspec', what would you suggest as an alternative?  Simply calling it 'cnquery and cnspec' could be confusing because on many systems we install a single 'mondoo' meta-package which installs both.  Furthermore, we don't support installation of only cnquery.

**Comment by tas50** [comment]
Much better. I'll get a more clear suggestion on the package name another time.
